name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bun-version:
          ["latest", "0.1.3", "latest"]
        misc-test-builds:
          [false, true]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun - Test Builds * ${{ matrix.misc-test-builds }}
        uses: ./
        with:
          bun-version: ${{ matrix.bun-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          misc-test-builds: ${{ matrix.misc-test-builds }}

      - name: Try bun
        run: bun --version

      - name: Change job status
        env:
          status: success